import { 
  ArticleOutlined, 
  SettingsOutlined, 
  DnsOutlined, 
  type SvgIconComponent, 
  QueryStatsOutlined, 
  EventNoteOutlined, 
  TerminalOutlined, 
  DevicesOutlined,
  CodeOutlined,
  WifiOutlined,
  LockOutlined,
  StorageOutlined,
  ShieldOutlined,
  FilterListOutlined,
  MapOutlined,
  AccountTreeOutlined,
  SecurityOutlined,
  FileCopyOutlined,
  AssignmentOutlined,
  TuneOutlined,
  AccessTimeOutlined,
  SwapHorizOutlined,
  BuildOutlined
} from '@mui/icons-material';

export const navIcons = {
  'QueryStats': QueryStatsOutlined,
  'EventNote': EventNoteOutlined,
  'Dns': DnsOutlined,
  'Devices': DevicesOutlined,
  'Article': ArticleOutlined,
  'Settings': SettingsOutlined,
  'Terminal': TerminalOutlined,
  'Code': CodeOutlined,
  'Wifi': WifiOutlined,
  'Lock': LockOutlined,
  'Database': StorageOutlined,
  'Shield': ShieldOutlined,
  'Filter': FilterListOutlined,
  'MapMarker': MapOutlined,
  'Sitemap': AccountTreeOutlined,
  'ShieldAlt': SecurityOutlined,
  'FileAlt': FileCopyOutlined,
  'ClipboardList': AssignmentOutlined,
  'SlidersH': TuneOutlined,
  'Clock': AccessTimeOutlined,
  'ExchangeAlt': SwapHorizOutlined,
  'Cog': BuildOutlined,
  'AccountTree': AccountTreeOutlined,
} as Record<string, SvgIconComponent>;
